version: "3"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "4321:4321"
    restart: always
    environment:
      CG_API_KEY: <CG_API_KEY>
      PORT: 4321
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:5173"
    restart: always
    depends_on:
      - backend
