version: "3"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    restart: always
    environment:
      CMC_API_KEY: ad33172e-865f-40d6-83a4-0b4d56cd4dcb
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - backend
