version: "3"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "4321:4321"
    restart: always
    environment:
      CMC_API_KEY: ad33172e-865f-40d6-83a4-0b4d56cd4dcb
      PORT: 4321
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:5173"
    restart: always
    depends_on:
      - backend
